servers:
- name: go-lsp
  languages:
  - go
  command: gopls
  args: []
  transport: stdio
  root_markers:
  - go.mod
  - go.sum
  priority: 1
  weight: 1.0
port: 8080
timeout: 45s
max_concurrent_requests: 150
multi_server_config:
  primary: null
  secondary: []
  selection_strategy: load_balance
  concurrent_limit: 3
  resource_sharing: true
  health_check_interval: 30s
  max_retries: 3
enable_concurrent_servers: true
max_concurrent_servers_per_language: 2
enable_smart_routing: true
smart_router_config:
  default_strategy: single_target_with_fallback
  method_strategies:
    textDocument/definition: single_target_with_fallback
    textDocument/documentSymbol: single_target_with_fallback
    textDocument/hover: primary_with_enhancement
    textDocument/references: multi_target_parallel
    workspace/symbol: broadcast_aggregate
  enable_performance_monitoring: true
  enable_circuit_breaker: true
  circuit_breaker_threshold: 5
  circuit_breaker_timeout: 30s
performance_config:
  enabled: false
  profile: development
  version: "1.0"
  caching:
    enabled: false
    global_ttl: 30m0s
    max_memory_usage_mb: 1024
    eviction_strategy: LRU
    response_cache:
      enabled: false
      ttl: 5m0s
      max_size: 1000
    semantic_cache:
      enabled: false
      ttl: 15m0s
      max_size: 500
    project_cache:
      enabled: false
      ttl: 30m0s
      max_size: 100
    symbol_cache:
      enabled: false
      ttl: 10m0s
      max_size: 2000
    completion_cache:
      enabled: false
      ttl: 2m0s
      max_size: 5000
    diagnostic_cache:
      enabled: false
      ttl: 1m0s
      max_size: 1000
    filesystem_cache:
      enabled: false
      ttl: 5m0s
      max_size: 1000
  resource_manager:
    memory_limits:
      max_heap_size_mb: 1024
      soft_limit_mb: 819
      per_server_limit_mb: 256
    cpu_limits:
      max_usage_percent: 80.0
      max_cores: 4
  timeouts:
    global_timeout: 30s
    default_timeout: 15s
    connection_timeout: 5s
  large_project:
    auto_detect_size: true
    file_count_threshold: 10000
    max_workspace_size_mb: 10240
    indexing_strategy: eager
    server_pool_scaling:
      min_servers: 1
      max_servers: 3
    background_indexing:
      enabled: false
  scip:
    enabled: false
    index_path: .scip
    refresh_interval: 30m0s
    fallback_to_lsp: true
    cache:
      enabled: false
      ttl: 30m0s
      max_size: 1000
    language_settings:
      go:
        enabled: false
        index_command:
        - scip-go
        index_timeout: 10m0s
        index_arguments:
        - --module-path
        - .
        - --output
        - .scip/index.scip
      python:
        enabled: false
        index_command:
        - scip-python
        index_timeout: 10m0s
        index_arguments:
        - --project-root
        - .
        - --output
        - .scip/index.scip
      typescript:
        enabled: false
        index_command:
        - scip-typescript
        index_timeout: 15m0s
        index_arguments:
        - --project-root
        - .
        - --output
        - .scip/index.scip
  storage:
    enabled: false
    version: "1.0"
    profile: development
    tiers:
      l1_memory:
        enabled: true
        capacity: 4GB
        max_entries: 100000
        eviction_policy: lru
        backend:
          type: memory
        performance:
          max_concurrency: 100
          timeout_ms: 1000
          batch_size: 100
          read_buffer_size: 8192
          write_buffer_size: 8192
          connection_pool_size: 10
          keep_alive: true
          prefetch_enabled: true
          prefetch_size: 10
        reliability:
          retry_count: 3
          retry_delay_ms: 100
          circuit_breaker:
            enabled: true
            failure_threshold: 10
            recovery_timeout: 30s
            half_open_requests: 5
            min_request_count: 20
          health_check_interval: 30s
          failure_threshold: 5
          recovery_timeout: 1m0s
      l2_disk:
        enabled: false
        capacity: 200GB
        max_entries: 1000000
        eviction_policy: lru
        backend:
          type: local_disk
          path: /opt/lsp-gateway/cache
        compression:
          enabled: true
          algorithm: snappy
          level: 3
          min_size: 1024
          threshold: 0.8
        performance:
          max_concurrency: 50
          timeout_ms: 5000
          batch_size: 50
          read_buffer_size: 32768
          write_buffer_size: 32768
          connection_pool_size: 5
          keep_alive: true
          prefetch_size: 5
        reliability:
          retry_count: 3
          retry_delay_ms: 200
          circuit_breaker:
            enabled: true
            failure_threshold: 5
            recovery_timeout: 1m0s
            half_open_requests: 3
            min_request_count: 10
          health_check_interval: 1m0s
          failure_threshold: 3
          recovery_timeout: 2m0s
    strategy:
      promotion_strategy:
        type: adaptive
        enabled: true
        min_access_count: 3
        min_access_frequency: 0.1
        access_time_window: 24h0m0s
        promotion_cooldown: 5m0s
        recency_weight: 0.4
        frequency_weight: 0.4
        size_weight: 0.2
        tier_thresholds:
          l1_to_l2: 0.7
          l2_to_l1: 0.3
      eviction_policy:
        type: lru
        enabled: true
        eviction_threshold: 0.85
        target_utilization: 0.75
        eviction_batch_size: 100
        access_age_threshold: 168h0m0s
        inactivity_threshold: 72h0m0s
        default_ttl: 24h0m0s
        max_ttl: 168h0m0s
        size_weight: 0.3
      access_tracking:
        enabled: true
        tracking_granularity: 1m0s
        history_retention: 168h0m0s
        max_tracked_keys: 100000
        analysis_interval: 1h0m0s
        min_sample_size: 10
        confidence_threshold: 0.7
        seasonality_detection: true
        trend_detection: true
        locality_tracking: true
      auto_optimization:
        enabled: false
        optimization_interval: 6h0m0s
        performance_threshold: 0.8
        capacity_threshold: 0.8
        auto_compaction: true
    monitoring:
      enabled: true
      metrics_interval: 30s
      health_interval: 1m0s
      log_level: info
      alert_thresholds:
        capacity_high: 0.9
        error_rate_high: 0.05
        hit_rate_low: 0.5
        latency_high: 1000.0
      export_format: prometheus
      retention_period: 168h0m0s
    maintenance:
      enabled: true
      schedule: 0 2 * * *
      maintenance_window:
        start_time: 02:00
        end_time: 04:00
        timezone: UTC
        days:
        - sunday
        - monday
        - tuesday
        - wednesday
        - thursday
        - friday
        - saturday
      compaction_enabled: true
      compaction_threshold: 0.3
      vacuum_enabled: true
      vacuum_interval: 24h0m0s
      cleanup_enabled: true
      cleanup_age: 168h0m0s
      backup_interval: 24h0m0s
      backup_retention: 720h0m0s
    security:
      access_control:
        enabled: false
        default_policy: deny
        rate_limiting:
          enabled: false
          requests_per_minute: 1000
          burst_size: 100
          window_size: 1m0s
      audit_logging:
        enabled: false
        log_level: info
        log_location: /var/log/lsp-gateway/audit.log
        retention_days: 30
        log_format: json
      data_classification:
        enabled: false
        default_level: internal
        classification_rules:
          "*.cert": restricted
          "*.key": confidential
          "*.secret": confidential
