servers:
    - name: jdtls-lsp
      languages:
        - java
      command: /home/skawn/.local/share/lsp-gateway/jdtls/bin/jdtls
      args: []
      transport: stdio
    - name: gopls-lsp
      languages:
        - go
      command: /home/skawn/go/bin/gopls
      args: []
      transport: stdio
    - name: pylsp-lsp
      languages:
        - python
      command: /home/skawn/.local/bin/pylsp
      args: []
      transport: stdio
    - name: typescript-language-server-lsp
      languages:
        - typescript
        - javascript
      command: /home/skawn/.nvm/versions/node/v22.17.1/bin/typescript-language-server
      args:
        - --stdio
      transport: stdio
port: 8080
max_concurrent_requests: 100
enable_concurrent_servers: false
max_concurrent_servers_per_language: 0
