servers:
    - name: typescript-language-server-lsp
      languages:
        - typescript
        - javascript
      command: typescript-language-server
      args:
        - --stdio
      transport: stdio
    - name: gopls-lsp
      languages:
        - go
      command: gopls
      args: []
      transport: stdio
    - name: pylsp-lsp
      languages:
        - python
      command: pylsp
      args: []
      transport: stdio
port: 8080
max_concurrent_requests: 100
enable_concurrent_servers: false
max_concurrent_servers_per_language: 0
