# Simple LSP Gateway Configuration
# References tests/data/configs/simple-test-repositories.yaml for test repositories

port: 8080

# Test repository configuration
repositories:
  config_file: "tests/data/configs/simple-test-repositories.yaml"
  base_directory: "./tests/data/repositories"

# LSP Server configurations
servers:
  - name: "go-lsp"
    languages: ["go"]
    command: "gopls"
    args: []
    transport: "stdio"
    
  - name: "python-lsp"
    languages: ["python"]
    command: "python"
    args: ["-m", "pylsp"]
    transport: "stdio"
    
  - name: "typescript-lsp"
    languages: ["typescript", "javascript"]
    command: "typescript-language-server"
    args: ["--stdio"]
    transport: "stdio"
    
  - name: "java-lsp"
    languages: ["java"]
    command: "jdtls"
    args: []
    transport: "stdio"

# Simple test configuration
testing:
  scenarios: ["basic", "standard"]
  timeout_seconds: 30
  parallel_execution: true
