# Simple LSP Test Configuration
# Basic testing scenarios for each language

# Test configuration
test_config:
  timeout_seconds: 30
  parallel_execution: true
  max_concurrent_tests: 4
  output_format: "json"

# Test scenarios
scenarios:
  basic:
    description: "Basic LSP functionality tests"
    tests:
      - "hover"
      - "definitions" 
      - "references"
  
  standard:
    description: "Standard LSP feature set"
    tests:
      - "hover"
      - "definitions"
      - "references"
      - "symbols"
      - "formatting"

# Language-specific test settings
languages:
  go:
    repository: "kubernetes"
    test_files:
      - "cmd/kubectl/kubectl.go"
      - "pkg/api/types.go"
    scenarios: ["basic", "standard"]
    
  python:
    repository: "django"
    test_files:
      - "django/__init__.py"
      - "django/db/models/base.py"
    scenarios: ["basic", "standard"]
    
  typescript:
    repository: "vscode"
    test_files:
      - "src/vs/editor/editor.main.ts"
      - "src/vs/workbench/workbench.main.ts"
    scenarios: ["basic", "standard"]
    
  java:
    repository: "spring-boot"
    test_files:
      - "spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java"
      - "spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/SpringBootApplication.java"
    scenarios: ["basic", "standard"]

# Expected results
expectations:
  hover:
    min_response_time_ms: 50
    max_response_time_ms: 1000
    required_fields: ["contents"]
    
  definitions:
    min_response_time_ms: 100
    max_response_time_ms: 2000
    required_fields: ["uri", "range"]
    
  references:
    min_response_time_ms: 200
    max_response_time_ms: 5000
    required_fields: ["uri", "range"]
    
  symbols:
    min_response_time_ms: 100
    max_response_time_ms: 3000
    required_fields: ["name", "kind"]
    
  formatting:
    min_response_time_ms: 100
    max_response_time_ms: 2000
    required_fields: ["range", "newText"]

# Reporting
reporting:
  formats: ["json", "html"]
  output_directory: "./test-results"
  include_performance_metrics: true
  include_error_details: true