# Minimal Configuration for LSP Gateway
# Single language example - Go only

servers:
  go:
    command: "gopls"
    args: ["serve"]
    working_dir: ""
    initialization_options: {}

# Unified Cache Configuration (Enabled by default)
cache:
  enabled: true
  storage_path: ".lsp-gateway/cache"
  max_memory_mb: 256
  ttl_hours: 24
  languages: ["go"]
  background_index: true
  health_check_minutes: 5
  eviction_policy: "lru"
  disk_cache: false