# Minimal Configuration for LSP Gateway
# Single language example - Go only

servers:
  go:
    command: "gopls"
    args: ["serve"]
    working_dir: ""
    initialization_options: {}

# SCIP Cache Configuration (Enabled by default)
cache:
  enabled: true
  storage_path: ".lsp-gateway/scip-cache"
  max_memory_mb: 256
  ttl: "24h"
  languages: ["go"]
  background_index: true
  health_check_interval: "5m"