# LSP Gateway CI/CD Test Configuration
port: 0  # Dynamic port allocation
timeout: 5s  # Very short timeout for CI
max_connections: 20

servers:
  # Minimal server configuration for CI
  - name: "ci-mock-lsp"
    languages: ["go"]
    command: "mock_lsp_server"
    args: []
    transport: "stdio"

# CI test specific settings  
ci_test:
  short_mode: true
  timeout_multiplier: 1
  concurrent_clients: 3
  requests_per_test: 20
