# LSP Gateway Performance Test Configuration
port: 0  # Dynamic port allocation for tests
timeout: 10s  # Shorter timeout for performance tests
max_connections: 50

servers:
  # Mock servers for performance testing
  - name: "perf-mock-lsp"
    languages: ["go", "python", "typescript", "javascript"]
    command: "mock_lsp_server"  # Embedded mock server
    args: []
    transport: "stdio"

# Performance test specific settings
performance_test:
  target_latency_ms: 100
  target_throughput_rps: 50
  target_memory_mb: 50
  concurrent_clients: 10
  requests_per_test: 100
  benchmark_time: "30s"
