# Python Repository LSP Validation Configuration
name: "Python Repository LSP Validation"
description: "Comprehensive LSP testing against real Python repositories"
timeout: 10m
parallel: true

servers:
  pylsp:
    name: "python-lsp-server"
    language: "python"
    command: "pylsp"
    transport: "stdio"
    start_timeout: 30s
    pre_warmup: true
    capabilities:
      - "textDocument/definition"
      - "textDocument/references"
      - "textDocument/hover"
      - "textDocument/documentSymbol"
      - "workspace/symbol"

repositories:
  - name: "django-repo"
    path: "./test-repositories/python/django"
    language: "python"
    description: "Django web framework repository"
    setup:
      commands:
        - "pip3 install -e . || true"
        - "pip3 install -r requirements.txt || true"
      timeout: 5m
    test_cases:
      # Definition tests
      - id: "python_definition_class"
        name: "Python class definition"
        method: "textDocument/definition"
        file: "django/http/request.py"
        position:
          line: 50
          character: 10
        expected:
          success: true
          definition:
            has_location: true
        tags: ["definition", "basic"]
        timeout: 30s

      # Reference tests
      - id: "python_references_import"
        name: "Python import references"
        method: "textDocument/references"
        file: "django/urls/__init__.py"
        position:
          line: 10
          character: 5
        params:
          includeDeclaration: true
        expected:
          success: true
          references:
            min_count: 1
        tags: ["references", "basic"]
        timeout: 45s

      # Hover tests
      - id: "python_hover_function"
        name: "Python function hover"
        method: "textDocument/hover"
        file: "django/utils/functional.py"
        position:
          line: 30
          character: 10
        expected:
          success: true
          hover:
            has_content: true
        tags: ["hover", "basic"]
        timeout: 30s

      # Document symbols
      - id: "python_document_symbols"
        name: "Python document symbols"
        method: "textDocument/documentSymbol"
        file: "django/db/models/base.py"
        expected:
          success: true
          symbols:
            min_count: 3
        tags: ["symbols", "basic"]
        timeout: 60s

      # Workspace symbols
      - id: "python_workspace_symbols"
        name: "Python workspace symbol search"
        method: "workspace/symbol"
        params:
          query: "Model"
        expected:
          success: true
          symbols:
            min_count: 1
        tags: ["workspace", "symbols"]
        timeout: 120s

  - name: "flask-repo"
    path: "./test-repositories/python/flask"
    language: "python"
    description: "Flask micro web framework repository"
    setup:
      commands:
        - "pip3 install -e . || true"
      timeout: 3m
    test_cases:
      # Definition tests
      - id: "flask_definition_app"
        name: "Flask app definition"
        method: "textDocument/definition"
        file: "src/flask/app.py"
        position:
          line: 100
          character: 15
        expected:
          success: true
          definition:
            has_location: true
        tags: ["definition", "flask"]
        timeout: 30s

      # Hover tests
      - id: "flask_hover_decorator"
        name: "Flask decorator hover"
        method: "textDocument/hover"
        file: "src/flask/app.py"
        position:
          line: 200
          character: 10
        expected:
          success: true
          hover:
            has_content: true
        tags: ["hover", "flask"]
        timeout: 30s

execution:
  max_concurrency: 2
  default_timeout: 60s
  retry_attempts: 2
  fail_fast: false

validation:
  strict_mode: false
  validate_types: true
  validate_positions: true
  validate_uris: true

reporting:
  formats: ["console", "json", "junit"]
  output_dir: "repo-validation-python"
  verbose: true
  include_timing: true