package cli

const (
	StatusFailed  = "failed"
	StatusWarning = "warning"
	StatusPassed  = "passed"
	StatusSkipped = "skipped"
	StatusUnknown = "Unknown"

	DefaultConfigFile = "config.yaml"

	// Command names
	CmdServer   = "server"
	CmdMCP      = "mcp"
	CmdVersion  = "version"
	CmdStatus   = "status"
	CmdDiagnose = "diagnose"
	CmdInstall  = "install"
	CmdVerify   = "verify"
	CmdSetup    = "setup"
	CmdConfig   = "config"

	FLAG_TIMEOUT                 = "timeout"
	FLAG_FORCE                   = "force"
	FLAG_DESCRIPTION_SERVER_PORT = "Server port"
	FLAG_DESCRIPTION_TIMEOUT     = "timeout"
	FLAG_DESCRIPTION_TRANSPORT   = "transport"
	FLAG_CONFIG                  = "config"
	FLAG_OUTPUT                  = "output"
	FLAG_JSON                    = "json"
	FLAG_VERBOSE                 = "verbose"
	FLAG_ALL                     = "all"
	FLAG_RUNTIME                 = "runtime"
	FLAG_SERVER                  = "server"
	FLAG_GATEWAY                 = "gateway"
	FLAG_PORT                    = "port"
	FLAG_READ                    = "read"
	FLAG_MAX_RETRIES             = "max-retries"
	FLAG_NO_INTERACTIVE          = "no-interactive"
	FLAG_CREATE                  = "create"
	FLAG_PROJECT                 = "project"
	FLAG_AUTO_DETECT_PROJECT     = "auto-detect-project"
	FLAG_GENERATE_PROJECT_CONFIG = "generate-project-config"
	
	// Bypass-related flags
	FLAG_BYPASS_ENABLED              = "bypass-enabled"
	FLAG_BYPASS_STRATEGY             = "bypass-strategy"
	FLAG_BYPASS_AUTO_CONSECUTIVE     = "bypass-auto-consecutive"
	FLAG_BYPASS_AUTO_CIRCUIT_BREAKER = "bypass-auto-circuit-breaker"
	FLAG_BYPASS_CONSECUTIVE_THRESHOLD = "bypass-consecutive-threshold"
	FLAG_BYPASS_RECOVERY_ATTEMPTS    = "bypass-recovery-attempts"
	FLAG_BYPASS_INTERACTIVE          = "bypass-interactive"
	FLAG_BYPASS_QUIET                = "bypass-quiet"

	FLAG_DESCRIPTION_CONFIG_PATH             = "Configuration file path"
	FLAG_DESCRIPTION_PROJECT_PATH            = "Project workspace path"
	FLAG_DESCRIPTION_AUTO_DETECT_PROJECT     = "Automatically detect project workspace"
	FLAG_DESCRIPTION_GENERATE_PROJECT_CONFIG = "Generate and save project-specific configuration"
	FLAG_DESCRIPTION_JSON_OUTPUT             = "Output in JSON format"
	FLAG_DESCRIPTION_JSON_RESULTS            = "Output results in JSON format"
	FLAG_DESCRIPTION_INSTALLATION_TIMEOUT    = "Installation timeout"
	
	// Bypass flag descriptions
	FLAG_DESCRIPTION_BYPASS_ENABLED              = "Enable global bypass functionality"
	FLAG_DESCRIPTION_BYPASS_STRATEGY             = "Default bypass strategy (fail_gracefully, fallback_server, cache_response, circuit_breaker, retry_with_backoff)"
	FLAG_DESCRIPTION_BYPASS_AUTO_CONSECUTIVE     = "Enable automatic bypass on consecutive failures"
	FLAG_DESCRIPTION_BYPASS_AUTO_CIRCUIT_BREAKER = "Enable automatic bypass on circuit breaker activation"
	FLAG_DESCRIPTION_BYPASS_CONSECUTIVE_THRESHOLD = "Number of consecutive failures before triggering bypass"
	FLAG_DESCRIPTION_BYPASS_RECOVERY_ATTEMPTS    = "Maximum number of recovery attempts"
	FLAG_DESCRIPTION_BYPASS_INTERACTIVE          = "Enable interactive mode for bypass decisions"
	FLAG_DESCRIPTION_BYPASS_QUIET                = "Enable quiet mode to reduce bypass-related logging"

	VALUE_CONFIGURATION  = "configuration"
	VALUE_CONFIG_YAML    = "config.yaml"
	VALUE_LOCALHOST_ZERO = "localhost:0"
	VALUE_TCP            = "tcp"
	VALUE_JSON_RPC_PATH  = "/jsonrpc"
	VALUE_PORT_FORMAT    = ":%d"
	VALUE_PATH_FORMAT    = "%s/%s"
	VALUE_YES            = "Yes"
	VALUE_N_A            = "N/A"

	FORMAT_EXECUTABLE_PATH       = "Executable Path: %s\n"
	FORMAT_VERIFIED_AT           = "  Verified At: %s\n"
	FORMAT_PATH                  = "  Path: %s\n"
	FORMAT_RUNTIME_NAME          = "Runtime: %s"
	FORMAT_SERVER_NAME           = "Server: %s"
	FORMAT_INSTALLING            = "Installing %s (%s)...\n"
	FORMAT_INSTALLING_RUNTIME    = "Installing %s runtime...\n"
	FORMAT_LIST_ITEM             = "    - %s\n"
	FORMAT_LIST_ITEM_DASH        = "  - %s\n"
	FORMAT_LIST_ITEM_BRACKET     = "  [%s] %s\n"
	FORMAT_VERSION               = "  Version: %s\n"
	FORMAT_VERSION_SHORT         = "Version: %s\n"
	FORMAT_BUILD_TIME            = "Build Time:   %s\n"
	FORMAT_METHOD                = "  Method: %s\n"
	FORMAT_DETAIL_ITEM           = "  - %s\n"
	FORMAT_ENV_VAR               = "  %s=%s\n"
	FORMAT_SOLUTION              = "    Solution: %s\n"
	FORMAT_DETAIL_INFO           = "\nDetailed Information:\n"
	FORMAT_SUMMARY               = "\nSummary:\n"
	FORMAT_TABLE_ROW             = "%s\t%s\t%s\t%s\n"
	FORMAT_KEY_VALUE             = "%s: %s\n"
	FORMAT_DETAILS               = "  Details:\n"
	FORMAT_DETAIL_VALUE          = "    %s: %v\n"
	FORMAT_COMPATIBLE            = "Compatible: %s\n"
	FORMAT_INSTALLATION_STATUS   = "Installation Status: %s\n"
	FORMAT_SECTION_SEPARATOR     = "========================================\n\n"
	FORMAT_SECTION_DIVIDER       = "======================================================="
	FORMAT_LINE_DIVIDER          = "─────────────────"
	FORMAT_ENVIRONMENT_VARS      = "\nEnvironment Variables:\n"
	FORMAT_ISSUES_FOUND          = "\nIssues Found:\n"
	FORMAT_RECOMMENDATIONS       = "\nRecommendations:\n"
	FORMAT_VERIFICATION_DURATION = "  Verification Duration: %v\n"
	FORMAT_ADDITIONAL_PATHS      = "  Additional Paths: %s\n"
	FORMAT_CONFIG_PATH           = "Config path: %s"
	FORMAT_FAILED_INSTALLATIONS  = "- Failed installations: %d\n"
	FORMAT_SPACES_FORMAT         = "    %s\n"

	LABEL_RUNTIME_STATUS     = "runtime status"
	LABEL_WARNINGS           = "Warnings:"
	LABEL_MESSAGES           = "  Messages:\n"
	LABEL_WARNING_ITEMS      = "  Warnings:\n"
	LABEL_ISSUES             = "  Issues:\n"
	LABEL_SUCCESS_CHECK      = "✓ Working"
	LABEL_ERROR_CHECK        = "✗ Error"
	LABEL_WARNING_CHECK      = "⚠ Issues"
	LABEL_NOT_INSTALLED      = "✗ Not Installed"
	LABEL_SUCCESS_RUNTIME    = "✓ %s runtime already installed and working (version: %s)\n"
	LABEL_SUCCESS_SERVER     = "✓ %s server already installed and working (version: %s)\n"
	LABEL_INSTALL_FAILED     = "✗ Installation failed after %v: %v\n"
	LABEL_INSTALL_ERRORS     = "✗ Installation completed with errors:\n"
	LABEL_WARNING_ITEM       = "    ⚠ %s\n"
	LABEL_FORCE_REINSTALL    = "  Use --force flag to reinstall\n"
	LABEL_CONFIGURATION_PATH = "Configuration path: %s\n"

	MSG_CHECK_INSTALL         = "Check if %s is installed"
	MSG_INSTALL_RUNTIME       = "Install %s runtime"
	MSG_INSTALL_SERVER        = "Install %s server"
	MSG_RUNTIME_NOT_INSTALLED = "%s runtime not installed"
	MSG_VERSION_NOT_MEET      = "%s version %s does not meet requirements"
	MSG_PROPERLY_INSTALLED    = "%s runtime %s is properly installed and compatible"
	MSG_SERVER_FUNCTIONAL     = "%s server is properly installed and functional"
	MSG_ADD_LANGUAGE_CONFIGS  = "Add language server configurations"
	MSG_TRY_INSTALL_SERVER    = "Try: lspg install server %s"
	MSG_TRY_INSTALL_RUNTIME   = "Try: lspg install runtime %s"

	ERROR_UNKNOWN_VALUE         = "unknown"
	ERROR_FILE_NOT_EXIST        = "file does not exist: %s"
	ERROR_PATH_IS_DIRECTORY     = "path is a directory, not a file: %s"
	ERROR_KILL_PROCESS          = "Kill process using port: sudo kill $(lsof -t -i:%d)"
	ERROR_CHECK_PORT_USAGE      = "Check what's using the port: lsof -i :%d"
	ERROR_ADDRESS_IN_USE        = "address already in use"
	ERROR_JSON_MARSHAL          = "failed to write table row: %w"
	ERROR_FLUSH_TABLE           = "failed to flush table output: %w"
	ERROR_WRITE_TABLE_HEADER    = "failed to write table header: %w"
	ERROR_WRITE_TABLE_SEPARATOR = "failed to write table separator: %w"
	ERROR_LOAD_CONFIGURATION    = "Failed to load configuration: %v"
	ERROR_VERIFY_SERVER         = "Failed to verify %s server: %v"
	ERROR_VERIFY_RUNTIME        = "Failed to verify %s runtime: %v"
	ERROR_UNSUPPORTED_RUNTIME   = "unsupported runtime '%s'. Supported runtimes: %s"
	ERROR_CLOSE_TEST_LISTENER   = "Error closing test listener: %v"
	ERROR_ALLOCATE_TEST_PORT    = "Failed to allocate test port: %v"
	ERROR_TEST_PORT_ALLOCATION  = "Failed to allocate test port: %v"

	SUGGESTION_LIST_DIRECTORY     = "List directory contents: ls -la %s"
	SUGGESTION_CHECK_PERMISSIONS  = "Check file permissions: ls -la %s"
	SUGGESTION_FIX_PERMISSIONS    = "Fix permissions: chmod 644 %s"
	SUGGESTION_SUPPORTED_SERVERS  = "Supported servers: %s"
	SUGGESTION_SUPPORTED_RUNTIMES = "Supported runtimes: %s"

	AUTO_INSTALL_SUGGESTION     = "Use automatic installation: lspg install runtime %s"
	SERVER_NOT_INSTALLED        = "%s server not installed"
	SERVER_COMPATIBILITY_ISSUES = "%s server installed but has compatibility issues"

	// Additional format strings
	FORMAT_SOLUTION_INSTRUCTION = "    Solution: %s\n"
	FORMAT_SPACES_INSTRUCTION   = "    %s\n"
	FORMAT_DOUBLE_NEWLINE       = "%s\n\n"

	// Directory and file operations (duplicate removed)

	// Common words
	WORD_RUNTIME  = "runtime"
	WORD_PLATFORM = "platform"
	WORD_SHARE    = "share"
	WORD_LIST     = "list"
	WORD_MAJOR    = "major"
	WORD_MINOR    = "minor"
)
