# Simple Comprehensive LSP Test Configuration 
# Simplified version for demonstrating the comprehensive test orchestration framework

name: "Simple Comprehensive LSP Test Suite"
description: "Simplified comprehensive LSP server validation across all languages"
version: "1.0"
timeout: "60m"
parallel: true
tags: ["comprehensive", "demo", "orchestration", "all-languages"]

# Test execution modes configuration
execution_modes:
  quick:
    description: "Quick validation tests for CI/CD"
    timeout: "15m"
    concurrency: 2
    include_benchmarks: false
    include_integration: false
    skip_performance: true
    test_count_limit: 25
    
  comprehensive:
    description: "Full comprehensive test suite"
    timeout: "60m"
    concurrency: 4
    include_benchmarks: true
    include_integration: true
    skip_performance: false
    
  benchmark:
    description: "Performance and benchmark focused testing"
    timeout: "45m"
    concurrency: 2
    include_benchmarks: true
    include_integration: false
    
  filtered:
    description: "Filtered testing based on criteria"
    timeout: "30m"
    concurrency: 2
    include_benchmarks: false
    include_integration: true

# Language server configurations for all supported languages
servers:
  gopls:
    name: "gopls"
    language: "go" 
    command: "gopls"
    transport: "stdio"
    start_timeout: "20s"
    shutdown_timeout: "10s"
    pre_warmup: true
    initialize_delay: "2s"
    health_check_interval: "30s"
    max_restarts: 3
    performance_thresholds:
      definition: "3s"
      references: "8s"
      hover: "2s"
      document_symbol: "5s"
      workspace_symbol: "10s"

  pylsp:
    name: "python-lsp-server"
    language: "python"
    command: "pylsp"
    transport: "stdio"
    start_timeout: "30s"
    shutdown_timeout: "15s"
    pre_warmup: true
    initialize_delay: "3s"
    health_check_interval: "45s"
    max_restarts: 3
    performance_thresholds:
      definition: "4s"
      references: "10s"
      hover: "3s"
      document_symbol: "7s"
      workspace_symbol: "15s"

  tsserver:
    name: "typescript-language-server"
    language: "typescript"
    command: "typescript-language-server"
    args: ["--stdio"]
    transport: "stdio"
    start_timeout: "25s"
    shutdown_timeout: "10s"
    pre_warmup: true
    initialize_delay: "2s"
    health_check_interval: "30s"
    max_restarts: 3
    performance_thresholds:
      definition: "3s"
      references: "8s"
      hover: "2s"
      document_symbol: "6s"
      workspace_symbol: "12s"

  jdtls:
    name: "jdtls"
    language: "java"
    command: "jdtls"
    transport: "stdio"
    start_timeout: "60s"
    shutdown_timeout: "20s"
    pre_warmup: true
    initialize_delay: "8s"
    health_check_interval: "60s"
    max_restarts: 2
    performance_thresholds:
      definition: "8s"
      references: "15s"
      hover: "5s"
      document_symbol: "10s"
      workspace_symbol: "20s"

# Repository configurations for comprehensive testing
repositories:
  go_scenarios:
    name: "go-comprehensive-scenarios"
    path: "./internal/testing/lsp/scenarios/testdata/go"
    language: "go"
    description: "Go comprehensive test scenarios"
    priority: "high"
    skip_if_missing: false
    categories: ["scenarios", "primary"]
    
  python_scenarios:
    name: "python-comprehensive-scenarios"
    path: "./internal/testing/lsp/scenarios/testdata/python"
    language: "python"
    description: "Python comprehensive test scenarios"
    priority: "high"
    skip_if_missing: false
    categories: ["scenarios", "primary"]
    
  typescript_scenarios:
    name: "typescript-comprehensive-scenarios"
    path: "./internal/testing/lsp/scenarios/testdata/typescript"
    language: "typescript"
    description: "TypeScript comprehensive test scenarios"
    priority: "high"
    skip_if_missing: false
    categories: ["scenarios", "primary"]
    
  java_scenarios:
    name: "java-comprehensive-scenarios"
    path: "./internal/testing/lsp/scenarios/testdata/java"
    language: "java"
    description: "Java comprehensive test scenarios"
    priority: "high"
    skip_if_missing: false
    categories: ["scenarios", "primary"]

# Comprehensive test suites organized by feature and complexity
test_suites:
  core_features:
    name: "Core LSP Feature Validation"
    description: "Comprehensive validation of all 5 core LSP features across all languages"
    priority: "critical"
    execution_mode: "parallel"
    timeout: "30m"
    
    feature_matrix:
      definition:
        description: "Go to Definition validation across all languages"
        methods: ["textDocument/definition"]
        languages: ["go", "python", "typescript", "java"]
        test_cases_per_language: 8
        performance_critical: true
        
      references:
        description: "Find References validation across all languages"  
        methods: ["textDocument/references"]
        languages: ["go", "python", "typescript", "java"]
        test_cases_per_language: 6
        performance_critical: true
        
      hover:
        description: "Hover Information validation across all languages"
        methods: ["textDocument/hover"] 
        languages: ["go", "python", "typescript", "java"]
        test_cases_per_language: 5
        performance_critical: false
        
      document_symbols:
        description: "Document Symbol validation across all languages"
        methods: ["textDocument/documentSymbol"]
        languages: ["go", "python", "typescript", "java"]
        test_cases_per_language: 4
        performance_critical: false
        
      workspace_symbols:
        description: "Workspace Symbol Search validation across all languages"
        methods: ["workspace/symbol"]
        languages: ["go", "python", "typescript", "java"] 
        test_cases_per_language: 3
        performance_critical: true

  performance_benchmarks:
    name: "LSP Performance Benchmarks"
    description: "Performance benchmarking and stress testing for all LSP features"
    priority: "high"
    execution_mode: "sequential"
    timeout: "45m"
    
    benchmark_categories:
      response_time:
        description: "Response time benchmarks for all methods"
        metrics: ["p50", "p95", "p99", "max"]
        target_duration: "15m"
        
      throughput:
        description: "Request throughput benchmarks"
        concurrent_requests: [1, 5, 10, 20]
        target_duration: "10m"
        
      memory_usage:
        description: "Memory usage tracking during operations"
        monitor_gc: true
        target_duration: "10m"
        
      large_workspace:
        description: "Large workspace performance testing"
        min_files: 1000
        target_duration: "10m"

  integration_tests:
    name: "Cross-Language Integration Tests"
    description: "Multi-language workspace and integration testing"
    priority: "medium"
    execution_mode: "mixed"
    timeout: "25m"
    
    scenarios:
      multi_language_workspace:
        description: "Test LSP servers in multi-language workspaces"
        languages: ["go", "python", "typescript", "java"]
        workspace_type: "mixed"
        
      server_lifecycle:
        description: "Server startup, shutdown, and recovery testing"
        languages: ["go", "python", "typescript", "java"]

# Filtering and execution control
filters:
  # Language filters
  go_only: 
    languages: ["go"]
    description: "Execute Go language tests only"
    
  python_only:
    languages: ["python"] 
    description: "Execute Python language tests only"
    
  typescript_only:
    languages: ["typescript"]
    description: "Execute TypeScript language tests only"
    
  java_only:
    languages: ["java"]
    description: "Execute Java language tests only"
    
  compiled_languages:
    languages: ["go", "java"]
    description: "Execute compiled language tests only"
    
  interpreted_languages:
    languages: ["python", "typescript"]
    description: "Execute interpreted language tests only"

  # Feature filters
  navigation_features:
    methods: ["textDocument/definition", "textDocument/references"]
    description: "Navigation-focused LSP features"
    
  information_features:
    methods: ["textDocument/hover", "textDocument/documentSymbol", "workspace/symbol"]
    description: "Information and symbol-focused LSP features"
    
  performance_critical:
    performance_critical: true
    description: "Performance-critical LSP features only"

  # Category filters
  scenarios_only:
    categories: ["scenarios"]
    description: "Scenario-based tests only"
    
  integration_only:
    categories: ["integration"]
    description: "Integration tests only"
    
  primary_only:
    categories: ["primary"]
    description: "Primary test repositories only"

# Validation and quality assurance configuration
validation:
  strict_mode: true
  validate_types: true
  validate_positions: true
  validate_uris: true
  validate_performance_thresholds: true
  
  quality_gates:
    minimum_pass_rate: 95.0
    maximum_performance_regression: 20.0
    required_coverage_features: ["definition", "references", "hover"]
    required_coverage_languages: ["go", "python", "typescript", "java"]

# Comprehensive reporting configuration
reporting:
  formats: ["console", "json", "junit", "html", "markdown"]
  output_dir: "test-results/comprehensive-lsp-tests"