name: Unit & Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-integration-tests:
    name: Unit & Integration Tests (${{ matrix.os }})
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
        check-latest: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Java LSP server (JDK + Eclipse JDT)
      id: cache-java-lsp
      uses: actions/cache@v4
      with:
        path: |
          ~/.lsp-gateway/tools/java
        key: ${{ runner.os }}-java-lsp-v1
        restore-keys: |
          ${{ runner.os }}-java-lsp-

    - name: Install dependencies
      run: go mod download

    - name: Build LSP Gateway
      run: |
        echo "🔨 Building LSP Gateway..."
        make local
        ls -la bin/

    - name: Install LSP servers
      run: |
        echo "📦 Installing all LSP servers..."
        
        # Note if Java is cached to save time
        if [ "${{ steps.cache-java-lsp.outputs.cache-hit }}" == "true" ]; then
          echo "✅ Using cached Java LSP server (JDK + Eclipse JDT)"
        fi
        
        # Install all LSP servers at once
        ./bin/lsp-gateway install all
        
        echo "✅ Verifying LSP server installations..."
        ./bin/lsp-gateway status

    - name: Run unit tests
      run: |
        echo "🧪 Running unit tests..."
        make test-unit

    - name: Run integration tests
      run: |
        echo "🧪 Running integration tests..."
        go test -v -timeout 600s ./tests/integration/...

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}
        path: |
          tests/**/*.log
        retention-days: 7